USE [ms2703333]
GO

/****** Object:  Table [dbo].[T_CUSTOMINFO]    Script Date: 09/14/2017 09:27:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_CUSTOMINFO](
	[CUSTNO] [varchar](10) NULL,
	[CUSTTYPE] [varchar](20) NULL,
	[CUSTNAME] [varchar](50) NULL,
	[COMPANY] [varchar](200) NULL,
	[POSITION] [varchar](50) NULL,
	[MOBILE] [varchar](15) NULL,
	[SIGNTIME] [datetime] NULL,
	[GETSOUVENIRSTIME] [datetime] NULL,
	[DINETIME] [datetime] NULL,
	[PRINTCOUNT] [int] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[T_CUSTOMINFO] ADD  CONSTRAINT [DF_T_CUSTOMINFO_PRINTCOUNT]  DEFAULT ((0)) FOR [PRINTCOUNT]
GO

